version: '3'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - ${WORDPRESS_PORT:-80}:80
    restart: always
    volumes:
      - ./:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:${MYSQL_PORT}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wpsite
  db:
    # form mac os
    # platform: linux/x86_64
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data: